# Generated by Django 3.2.7 on 2021-09-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='学期名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学期表',
                'verbose_name_plural': '学期表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='科目名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '科目表',
                'verbose_name_plural': '科目表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='话题名称')),
                ('content', django_quill.fields.QuillField(verbose_name='富文本内容')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击次数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '话题表',
                'verbose_name_plural': '话题表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', django_quill.fields.QuillField(verbose_name='评论内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'ordering': ['-id'],
            },
        ),
    ]
